---
- name: Install Node.js and Git
  apt:
    name:
      - nodejs
      - npm
      - git
    state: present
    update_cache: yes

- name: Clone backend repository
  git:
    repo: "https://github.com/heroku/node-js-sample.git"
    dest: /home/k/backend
    version: master
    force: yes

- name: Install npm dependencies
  npm:
    path: /home/k/backend
    production: yes

- name: Start backend app with PM2
  npm:
    name: pm2
    global: yes
  notify: Restart backend

